**Parte 1: Análisis Básico con NumPy**

En esta primera parte del proyecto, los estudiantes realizarán un análisis preliminar del dataset utilizando NumPy. El objetivo es familiarizarse con los datos y realizar operaciones básicas de manipulación y análisis.

**Configuración Inicial del Proyecto:**

Crea un repositorio en GitHub para tu proyecto.

Configura dos ramas en tu repositorio: main y development.

Agrega un archivo README.md con una descripción del proyecto, instrucciones de instalación y uso.

**Carga y Preprocesamiento de Datos:**

Carga los datos del archivo CSV utilizando NumPy.

Realiza un preprocesamiento básico para asegurarte de que los datos estén limpios y listos para su análisis.

**Exploración de Datos:**

Calcula el total de ventas por categoría de producto.

Calcula el promedio de ventas diarias por categoría de producto.

Identifica las categorías de productos con mayores y menores ventas.

**Manipulación de Datos:**

Filtra los datos para mostrar solo las ventas de una categoría de producto específica.

Realiza operaciones de suma, resta, multiplicación y división en los datos para obtener estadísticas adicionales.

In [3]:
import pandas as pd
import numpy as np

In [10]:
def cargar_datos(ruta_archivo):
    # Carga los datos del archivo CSV utilizando NumPy
    datos = np.genfromtxt(ruta_archivo, delimiter=',', skip_header=1)
    return datos

if __name__ == "__main__":
    ruta_archivo = '../data/retail_sales_dataset.csv'
    datos = cargar_datos(ruta_archivo)
    print(datos)

[[   1.   nan   nan ...    3.   50.  150.]
 [   2.   nan   nan ...    2.  500. 1000.]
 [   3.   nan   nan ...    1.   30.   30.]
 ...
 [ 998.   nan   nan ...    4.   25.  100.]
 [ 999.   nan   nan ...    3.   50.  150.]
 [1000.   nan   nan ...    4.   30.  120.]]

In [11]:
columnas = datos[0]
print(columnas)

[  1.  nan  nan  nan  34.  nan   3.  50. 150.]

In [12]:
filas = datos[1:6]
print(filas)

[[   2.   nan   nan   nan   26.   nan    2.  500. 1000.]
 [   3.   nan   nan   nan   50.   nan    1.   30.   30.]
 [   4.   nan   nan   nan   37.   nan    1.  500.  500.]
 [   5.   nan   nan   nan   30.   nan    2.   50.  100.]
 [   6.   nan   nan   nan   45.   nan    1.   30.   30.]]

Se continuó el ejercicio con pandas, ya que resultó engorroso visualizar los datos con numpy

In [14]:
df = pd.read_csv('../data/retail_sales_dataset.csv')
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [15]:
df.shape

(1000, 9)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

**Transaction ID**: un identificador único para cada transacción, que permite su seguimiento y consulta.

**Date**: la fecha en la que se realizó la transacción, lo que ofrece información sobre las tendencias de ventas a lo largo del tiempo.

**Customer ID**: un identificador único para cada cliente, que permite realizar análisis centrados en el cliente.

**Gender**: El género del cliente (hombre/mujer), lo que ofrece información sobre los patrones de compra según el género.

**Age**: La edad del cliente, lo que facilita la segmentación y el análisis de las influencias relacionadas con la edad.

**Product Category**: La categoría del producto comprado (por ejemplo, electrónica, ropa, belleza), lo que ayuda a comprender las preferencias de producto.

**Quantity**: El número de unidades del producto comprado, lo que contribuye a obtener información sobre los volúmenes de compra.


**Price per Unit**: El precio de una unidad del producto, que ayuda en los cálculos relacionados con el gasto total.

**Total Amount**: El valor monetario total de la transacción, que muestra el impacto financiero de cada compra.

In [17]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [18]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [19]:
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [20]:
nulos = df.isnull().sum()
nulos

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [21]:
duplicados = df.duplicated().sum()
duplicados

np.int64(0)

Calcula el total de ventas por categoría de producto.

In [22]:
total_de_ventas_por_categoria = df.groupby('Product Category')['Total Amount'].sum()
total_de_ventas_por_categoria

Product Category
Beauty         143515
Clothing       155580
Electronics    156905
Name: Total Amount, dtype: int64

La venta de electronics recaudó más dinero que la venta de los otros productos

Tarea: Calcula el promedio de ventas diarias por categoría de producto.

In [23]:
promedio_ventas_diarias_por_categoria = df.groupby(['Product Category', 'Date'])['Total Amount'].mean()
promedio_ventas_diarias_por_categoria

Product Category  Date
Beauty            2023-01-01    1500.0
                  2023-01-02      25.0
                  2023-01-03     600.0
                  2023-01-04     545.0
                  2023-01-05      50.0
                                 ...
Electronics       2023-12-27     600.0
                  2023-12-28      37.5
                  2023-12-29     100.0
                  2023-12-31      50.0
                  2024-01-01      30.0
Name: Total Amount, Length: 655, dtype: float64

Tarea: Identifica las categorías de productos con mayores y menores ventas.

*Nota: Aquí pedí ayuda a la IA porque no entendía que me estaban pidiendo.

In [24]:
producto_con_mayor_venta = total_de_ventas_por_categoria.max()
categoria_mayor_venta = total_de_ventas_por_categoria.idxmax()

print(f"Categoria con mayor venta: {categoria_mayor_venta} y su total: {producto_con_mayor_venta}")

Categoria con mayor venta: Electronics y su total: 156905

In [25]:
producto_con_menor_venta = total_de_ventas_por_categoria.min()
categoria_menor_venta = total_de_ventas_por_categoria.idxmin()

print(f"Categoria con menor venta: {categoria_menor_venta} y su total: {producto_con_menor_venta}")

Categoria con menor venta: Beauty y su total: 143515

Tarea: Filtra los datos para mostrar solo las ventas de una categoría de producto específica.

In [26]:
#Categoría Beauty
ventas_beauty = df[df['Product Category'] == 'Beauty']
ventas_beauty

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
11,12,2023-10-30,CUST012,Male,35,Beauty,3,25,75
20,21,2023-01-14,CUST021,Female,50,Beauty,1,500,500
...,...,...,...,...,...,...,...,...,...
981,982,2023-12-19,CUST982,Female,46,Beauty,3,30,90
989,990,2023-05-25,CUST990,Female,58,Beauty,2,500,1000
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100

Tarea: Realiza operaciones de suma, resta, multiplicación y división en los datos para obtener estadísticas adicionales.

*Realicé algunos filtros adicionales que pensé podría usar después para realizar las operaciones

In [27]:
cantidades_por_categoria = df.groupby('Product Category')['Quantity'].sum() #detalle de las cantidades vendidas por cada categoria
cantidades_por_categoria

Product Category
Beauty         771
Clothing       894
Electronics    849
Name: Quantity, dtype: int64

La ropa fue la categoría más vendida por unidad

In [28]:
transacciones_por_genero = df['Gender'].value_counts()
transacciones_por_genero

Gender
Female    510
Male      490
Name: count, dtype: int64

Las mujeres hicieron hicieron más compras que los hombres

In [29]:
compras_por_genero = df.groupby('Gender')['Total Amount'].sum()
compras_por_genero

Gender
Female    232840
Male      223160
Name: Total Amount, dtype: int64

Las mujeres gastaron más que los hombres

In [30]:
gasto_promedio_por_compra = df.groupby('Gender')['Total Amount'].mean()
gasto_promedio_por_compra

Gender
Female    456.549020
Male      455.428571
Name: Total Amount, dtype: float64

En promedio las mujeres gastaron un poco más que los hombres

In [31]:
total_ventas = df['Total Amount'].sum()
print(f"La cantidad total de todas las ventas es: {total_ventas}")

La cantidad total de todas las ventas es: 456000

In [32]:
cantidad_electronics = cantidades_por_categoria['Electronics']
print(f"La cantidad de productos electrónicos vendidos es: {cantidad_electronics}")

La cantidad de productos electrónicos vendidos es: 849

In [33]:
suma = df['Quantity'].sum()
print(f"La cantidad total de productos vendidos es: {suma}")

resta = suma - cantidad_electronics
print(f"Las cantidades vendidas entre Beauty y Clothing es: {resta}")

multiplicacion = total_ventas * 0.9
print(f"El total de ventas con un 10% de descuento es: {multiplicacion}")

La cantidad total de productos vendidos es: 2514
Las cantidades vendidas entre Beauty y Clothing es: 1665
El total de ventas con un 10% de descuento es: 410400.0