**Parte 1: Análisis Básico con NumPy**

**Parte II: Análisis Exploratorio con Pandas**

In [34]:
import pandas as pd
import numpy as np

Carga el archivo retail_sales.csv en un DataFrame de Pandas:

In [35]:
url = 'https://drive.google.com/uc?id=1c27mUHIqUhCfqVXcABhY9dnxyJ2y4d24'
df = pd.read_csv(url)
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [36]:
df.shape

(1000, 9)

## Columnas:

**Transaction ID**: un identificador único para cada transacción, que permite su seguimiento y consulta.

**Date**: la fecha en la que se realizó la transacción, lo que ofrece información sobre las tendencias de ventas a lo largo del tiempo.

**Customer ID**: un identificador único para cada cliente, que permite realizar análisis centrados en el cliente.

**Gender**: El género del cliente (hombre/mujer), lo que ofrece información sobre los patrones de compra según el género.

**Age**: La edad del cliente, lo que facilita la segmentación y el análisis de las influencias relacionadas con la edad.

**Product Category**: La categoría del producto comprado (por ejemplo, electrónica, ropa, belleza), lo que ayuda a comprender las preferencias de producto.

**Quantity**: El número de unidades del producto comprado, lo que contribuye a obtener información sobre los volúmenes de compra.


**Price per Unit**: El precio de una unidad del producto, que ayuda en los cálculos relacionados con el gasto total.

**Total Amount**: El valor monetario total de la transacción, que muestra el impacto financiero de cada compra.

Muestra las primeras 10 filas del DataFrame para confirmar que los datos se han cargado correctamente:

In [37]:
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

Muestra las últimas 5 filas del DataFrame:

In [38]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

Utiliza el método info() para obtener información general sobre el DataFrame, incluyendo el número de entradas, nombres de las columnas, tipos de datos y memoria utilizada:

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

Genera estadísticas descriptivas del DataFrame utilizando el método describe():

In [40]:
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

Inspecciona los tipos de datos de cada columna utilizando el atributo dtypes:

In [41]:
df.dtypes

Transaction ID      int64
Date                  str
Customer ID           str
Gender                str
Age                 int64
Product Category      str
Quantity            int64
Price per Unit      int64
Total Amount        int64
dtype: object

In [42]:
nulos = df.isnull().sum()
nulos

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

No hay datos nulos.

In [43]:
duplicados = df.duplicated().sum()
duplicados

np.int64(0)

No hay datos duplicados

Cuenta los valores únicos en la columna Producto utilizando el método value_counts():

In [44]:
valores_unicos_producto = df['Product Category'].value_counts()
valores_unicos_producto

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

Muestra todos los valores únicos en la columna Tienda utilizando el método unique():

*No existe la columna Tienda, sin embargo, decidi usar la columna edad para obtener los valores únicos.

In [45]:
valores_unicos_edad = df['Age'].unique()
valores_unicos_edad

array([34, 26, 50, 37, 30, 45, 46, 63, 52, 23, 35, 22, 64, 42, 19, 27, 47,
       62, 18, 49, 28, 38, 43, 39, 44, 51, 58, 48, 55, 20, 40, 54, 36, 31,
       21, 57, 25, 56, 29, 61, 32, 41, 59, 60, 33, 53, 24])

Filtra el DataFrame para mostrar solo las filas donde las ventas (Ventas) sean mayores a 50:

In [46]:
ventas_mayor_a50 = df[df['Total Amount'] > 50]
ventas_mayor_a50

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
...,...,...,...,...,...,...,...,...,...
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

Filtra el DataFrame para mostrar solo las filas donde el precio (Precio) sea menor a 0.5:

In [47]:
precio_menor_a50 = df[df['Price per Unit'] < 0.5]
precio_menor_a50

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount]
Index: []

No hay datos, por lo tanto no existen productos con precios < 0.5.

Utilizando el método query(), filtra el DataFrame para mostrar las filas donde el producto sea Manzanas y las ventas sean mayores a 30:

*No existe el prodcuto manzana, decidí usar Electronics para hacer la query.

In [48]:
ventas_electronics_mayor_a30 = df.query("`Product Category` == 'Electronics' and `Total Amount` > 30")
ventas_electronics_mayor_a30

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
12,13,2023-08-05,CUST013,Male,22,Electronics,3,500,1500
14,15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000
17,18,2023-04-30,CUST018,Female,47,Electronics,2,25,50
...,...,...,...,...,...,...,...,...,...
984,985,2023-05-30,CUST985,Female,19,Electronics,2,25,50
991,992,2023-08-21,CUST992,Female,57,Electronics,2,30,60
992,993,2023-02-06,CUST993,Female,48,Electronics,3,50,150
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

Selecciona y muestra solo las columnas Producto y Ventas del DataFrame:

In [49]:
seleccion_de_columnas = df[['Product Category', 'Total Amount']]
seleccion_de_columnas

    Product Category  Total Amount
0             Beauty           150
1           Clothing          1000
2        Electronics            30
3           Clothing           500
4             Beauty           100
..               ...           ...
995         Clothing            50
996           Beauty            90
997           Beauty           100
998      Electronics           150
999      Electronics           120

[1000 rows x 2 columns]

Utilizando loc[], selecciona y muestra las filas de la 5 a la 10 (inclusive) y las columnas Producto y Tienda:

*No existe la columna Tienda, decidí usar la columna precio por unidad, para ver los precios de los productos.

In [50]:
loc_para_mostrar_filas = df.loc[5:10, ['Product Category', 'Price per Unit']]
loc_para_mostrar_filas

   Product Category  Price per Unit
5            Beauty              30
6          Clothing              25
7       Electronics              25
8       Electronics             300
9          Clothing              50
10         Clothing              50

Utilizando iloc[], selecciona y muestra las primeras 5 filas y las primeras 3 columnas del DataFrame:

In [51]:
iloc_muestra_filas_y_columnas = df.iloc[0:5, 0:3]
iloc_muestra_filas_y_columnas

   Transaction ID        Date Customer ID
0               1  2023-11-24     CUST001
1               2  2023-02-27     CUST002
2               3  2023-01-13     CUST003
3               4  2023-05-21     CUST004
4               5  2023-05-06     CUST005