**Parte I: Análisis Básico con NumPy**

**Parte II: Análisis Exploratorio con Pandas**

**Parte III: Transformación y Análisis Avanzado de Datos con Pandas**

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://drive.google.com/uc?id=1c27mUHIqUhCfqVXcABhY9dnxyJ2y4d24'
df = pd.read_csv(url)
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

## Columnas:

**Transaction ID**: un identificador único para cada transacción, que permite su seguimiento y consulta.

**Date**: la fecha en la que se realizó la transacción, lo que ofrece información sobre las tendencias de ventas a lo largo del tiempo.

**Customer ID**: un identificador único para cada cliente, que permite realizar análisis centrados en el cliente.

**Gender**: El género del cliente (hombre/mujer), lo que ofrece información sobre los patrones de compra según el género.

**Age**: La edad del cliente, lo que facilita la segmentación y el análisis de las influencias relacionadas con la edad.

**Product Category**: La categoría del producto comprado (por ejemplo, electrónica, ropa, belleza), lo que ayuda a comprender las preferencias de producto.

**Quantity**: El número de unidades del producto comprado, lo que contribuye a obtener información sobre los volúmenes de compra.


**Price per Unit**: El precio de una unidad del producto, que ayuda en los cálculos relacionados con el gasto total.

**Total Amount**: El valor monetario total de la transacción, que muestra el impacto financiero de cada compra.

In [3]:
df.shape

(1000, 9)

In [4]:
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

In [5]:
df.tail(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
990,991,2023-12-26,CUST991,Female,34,Clothing,2,50,100
991,992,2023-08-21,CUST992,Female,57,Electronics,2,30,60
992,993,2023-02-06,CUST993,Female,48,Electronics,3,50,150
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000
994,995,2023-04-30,CUST995,Female,41,Clothing,1,30,30
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [7]:
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [8]:
nulos = df.isnull().sum()
nulos

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

No hay datos nulos.

In [9]:
duplicados = df.duplicated().sum()
duplicados

np.int64(0)

No hay datos duplicados

## Transformación de Datos

In [10]:
df2 = df.copy()

Primero pasamos la fecha a tipo datetime, ya que actualmente está en object.

In [11]:
df2['Date'] = pd.to_datetime(df2['Date'])

In [12]:
df2.dtypes

Transaction ID               int64
Date                datetime64[us]
Customer ID                    str
Gender                         str
Age                          int64
Product Category               str
Quantity                     int64
Price per Unit               int64
Total Amount                 int64
dtype: object

**Crea nuevas columnas**: **Basándonos en los datos existentes, crea nuevas columnas que sean útiles para el análisis. Por ejemplo, calcula el ingreso total por venta y normaliza las ventas.**

Le sumaremos el IVA  las ventas

In [13]:
df2['Total Amount IVA'] = df2['Total Amount'] * 1.19
df2

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Total Amount IVA
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,178.5
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,1190.0
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,35.7
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,595.0
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,119.0
...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,59.5
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,107.1
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,119.0
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,178.5
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,142.8

Normalización de Total Amount

In [14]:
df2['Total Amount Normalizado'] = (df2['Total Amount'] - df2['Total Amount'].min() / (df2['Total Amount'].max() - df2['Total Amount'].min())).round(1)
df2

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Total Amount IVA,Total Amount Normalizado
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,178.5,150.0
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,1190.0,1000.0
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,35.7,30.0
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,595.0,500.0
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,119.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,59.5,50.0
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,107.1,90.0
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,119.0,100.0
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,178.5,150.0
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,142.8,120.0

**Clasifica los datos**: **Crea una columna que clasifique las ventas en categorías significativas (e.g., ‘Alta’, ‘Media’, ‘Baja’).**

Primero vemos cual es el valor máximo y mínimo de ventas para hacer la clasificación

In [15]:
df2['Total Amount'].max()

np.int64(2000)

In [16]:
df2['Total Amount'].min()

np.int64(25)

In [17]:
def categoria_ventas(total_amount):
  if total_amount < 700:
    return 'Baja'
  elif total_amount < 1000:
    return 'Media'
  else:
    return 'Alta'

In [18]:
df2['Total Amount Categoría'] = df2['Total Amount'].apply(categoria_ventas)
df2

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Total Amount IVA,Total Amount Normalizado,Total Amount Categoría
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,178.5,150.0,Baja
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,1190.0,1000.0,Alta
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,35.7,30.0,Baja
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,595.0,500.0,Baja
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,119.0,100.0,Baja
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,59.5,50.0,Baja
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,107.1,90.0,Baja
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,119.0,100.0,Baja
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,178.5,150.0,Baja
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,142.8,120.0,Baja

In [19]:
reorden_columnas =['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age', 'Product Category', 'Quantity', 'Price per Unit', 'Total Amount', 'Total Amount Categoría', 'Total Amount IVA', 'Total Amount Normalizado' ]

In [20]:
df2 = df2[reorden_columnas]
df2

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Total Amount Categoría,Total Amount IVA,Total Amount Normalizado
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Baja,178.5,150.0
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Alta,1190.0,1000.0
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,Baja,35.7,30.0
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Baja,595.0,500.0
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Baja,119.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,Baja,59.5,50.0
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,Baja,107.1,90.0
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,Baja,119.0,100.0
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,Baja,178.5,150.0
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,Baja,142.8,120.0

## Agrupación y Agregación

**Agrupación por múltiples columnas**: Realiza agrupaciones por categorías como producto y tienda, producto y mes, etc.

Sumatoria de ventas por cada categoría

In [21]:
producto_y_ventas = df2.groupby('Product Category')['Total Amount'].sum()
producto_y_ventas

Product Category
Beauty         143515
Clothing       155580
Electronics    156905
Name: Total Amount, dtype: int64

Ventas totales por genero.

In [22]:
genero_y_ventas = df2.groupby('Gender')['Total Amount'].sum()
genero_y_ventas

Gender
Female    232840
Male      223160
Name: Total Amount, dtype: int64

**Aplicar funciones de agregación**: Utiliza funciones como sum, mean, count, min, max, std, y var para obtener estadísticas descriptivas de cada grupo.

In [23]:
df2.groupby('Total Amount Categoría')['Total Amount'].agg(['mean', 'count', 'min', 'max', 'std', 'var'])

,mean,count,min,max,std,var
Total Amount Categoría,,,,,,
Alta,1419.801980,202,1000,2000,373.638770,139605.930742
Baja,154.076087,736,25,600,157.650788,24853.771074
Media,900.000000,62,900,900,0.000000,0.000000

## Análisis Personalizado con apply

**Función personalizada**: Aplica funciones personalizadas para realizar análisis específicos que no se pueden lograr con las funciones de agregación estándar.

Vemos las edades mínimas y máximas para hacer la clasificación por edad

In [24]:
df2['Age'].max()

np.int64(64)

In [25]:
df2['Age'].min()

np.int64(18)

In [26]:
def categoria_edad(age):
  if age < 18:
    return "Menor de edad"
  elif age < 30:
    return "Joven adulto"
  elif age < 60:
    return "Adulto"
  else:
    return "Adulto mayor"

In [27]:
df2['Age Category'] = df2['Age'].apply(categoria_edad)
df2

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Total Amount Categoría,Total Amount IVA,Total Amount Normalizado,Age Category
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Baja,178.5,150.0,Adulto
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Alta,1190.0,1000.0,Joven adulto
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,Baja,35.7,30.0,Adulto
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Baja,595.0,500.0,Adulto
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Baja,119.0,100.0,Adulto
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,Baja,59.5,50.0,Adulto mayor
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,Baja,107.1,90.0,Adulto
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,Baja,119.0,100.0,Joven adulto
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,Baja,178.5,150.0,Adulto
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,Baja,142.8,120.0,Adulto

In [28]:
reordenar_columnas =['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age', 'Age Category', 'Product Category', 'Quantity', 'Price per Unit', 'Total Amount', 'Total Amount Categoría', 'Total Amount IVA', 'Total Amount Normalizado' ]

In [29]:
df2 = df2[reordenar_columnas]
df2

,Transaction ID,Date,Customer ID,Gender,Age,Age Category,Product Category,Quantity,Price per Unit,Total Amount,Total Amount Categoría,Total Amount IVA,Total Amount Normalizado
0,1,2023-11-24,CUST001,Male,34,Adulto,Beauty,3,50,150,Baja,178.5,150.0
1,2,2023-02-27,CUST002,Female,26,Joven adulto,Clothing,2,500,1000,Alta,1190.0,1000.0
2,3,2023-01-13,CUST003,Male,50,Adulto,Electronics,1,30,30,Baja,35.7,30.0
3,4,2023-05-21,CUST004,Male,37,Adulto,Clothing,1,500,500,Baja,595.0,500.0
4,5,2023-05-06,CUST005,Male,30,Adulto,Beauty,2,50,100,Baja,119.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Adulto mayor,Clothing,1,50,50,Baja,59.5,50.0
996,997,2023-11-17,CUST997,Male,52,Adulto,Beauty,3,30,90,Baja,107.1,90.0
997,998,2023-10-29,CUST998,Female,23,Joven adulto,Beauty,4,25,100,Baja,119.0,100.0
998,999,2023-12-05,CUST999,Female,36,Adulto,Electronics,3,50,150,Baja,178.5,150.0
999,1000,2023-04-12,CUST1000,Male,47,Adulto,Electronics,4,30,120,Baja,142.8,120.0

**Ejemplo de uso avanzado**: Calcula la desviación de cada venta respecto a la media de su grupo.

**Nota: aquí le pedí ayuda a la IA porque no entendía que me preguntaban.

Compararemos cada venta con el promedio del grupo al que pertenece (valor individual - promedio del grupo)

In [30]:
df2['Desviacion'] = ((df2['Total Amount'] - df2.groupby('Total Amount Categoría')['Total Amount'].transform('mean'))).round(2)

In [31]:
df2

,Transaction ID,Date,Customer ID,Gender,Age,Age Category,Product Category,Quantity,Price per Unit,Total Amount,Total Amount Categoría,Total Amount IVA,Total Amount Normalizado,Desviacion
0,1,2023-11-24,CUST001,Male,34,Adulto,Beauty,3,50,150,Baja,178.5,150.0,-4.08
1,2,2023-02-27,CUST002,Female,26,Joven adulto,Clothing,2,500,1000,Alta,1190.0,1000.0,-419.80
2,3,2023-01-13,CUST003,Male,50,Adulto,Electronics,1,30,30,Baja,35.7,30.0,-124.08
3,4,2023-05-21,CUST004,Male,37,Adulto,Clothing,1,500,500,Baja,595.0,500.0,345.92
4,5,2023-05-06,CUST005,Male,30,Adulto,Beauty,2,50,100,Baja,119.0,100.0,-54.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Adulto mayor,Clothing,1,50,50,Baja,59.5,50.0,-104.08
996,997,2023-11-17,CUST997,Male,52,Adulto,Beauty,3,30,90,Baja,107.1,90.0,-64.08
997,998,2023-10-29,CUST998,Female,23,Joven adulto,Beauty,4,25,100,Baja,119.0,100.0,-54.08
998,999,2023-12-05,CUST999,Female,36,Adulto,Electronics,3,50,150,Baja,178.5,150.0,-4.08
999,1000,2023-04-12,CUST1000,Male,47,Adulto,Electronics,4,30,120,Baja,142.8,120.0,-34.08

resultados columna "desviacion"

positivo: venta sobre el promedio de su categoría

negativo: venta bajo el promedio

cercano a 0: venta cercana al promedio del grupo